version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - stage.env
    volumes:
      - ./src:/usr/app/src
    command: yarn start
    labels:
      - traefik.http.routers.app.rule=Host(`staging.prontoentregue.com.br`)
  db:
    ports:
      - "3306:3306"
  traefik:
    image: traefik:2.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - 8080
    command: --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock