version: "3.7"

services:
  app:
    build: .
    labels:
      - traefik.http.routers.app.rule=Host(`api.prontoentregue.com.br`)
    restart: always
    env_file:
      - prod.env
    ports:
    - "4000:4000"
    command: yarn start
    links:
      - "db:database"
      - "redis"
    environment:
      - TZ=America/Sao_Paulo
  db:
    build: ./mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=PSqYX3HuNc
      - MYSQL_DATABASE=pronto_entregue
      - MYSQL_USER=prontouser
      - MYSQL_PASSWORD=EctIonwaRTRU
  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
  traefik:
    image: traefik:2.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      #- "443:443"
    expose:
      - 8080
    command: --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock