version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - prod.env
    labels:
      - traefik.http.routers.app.rule=Host(`api.prontoentregue.com.br`)
    ports:
      - "4000:4000"
      - "9229:9229"
    command: yarn start
    links:
      - "redis"
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_MAX_USER_CONNECTIONS=66
  traefik:
    image: traefik:2.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - 8080
    command: --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:latest
    restart: on-failure
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"