version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./src:/usr/app/src
    env_file:
      - dev.env
    ports:
    - "4000:4000"
    command: yarn dev
    links:
      - "db:database"
      - "redis"
    environment:
      - TZ=America/Sao_Paulo
  db:
    build: ./mysql
    ports:
      - "5000:3306"
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=PSqYX3HuNc
      - MYSQL_DATABASE=pronto_entregue
      - MYSQL_USER=prontouser
      - MYSQL_PASSWORD=EctIonwaRTRU
  redis:
    image: redis:latest
    restart: on-failure
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"